name: docs

on:
  push:
    branches: [ develop, release ]
    paths:
      - docs
      - mkdocs.yml
      - .github/workflows/docs.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Update pip
      run: python -m pip install -U pip setuptools
    - name: Install dependencies
      run: pip install -Ur docs/requirements.txt
    - name: Build docs (latest)
      if: ${{ github.ref == 'refs/heads/release' }}
      run: mike deploy -u $(git describe --tags --abbrev=0) latest
    - name: Build docs (develop)
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: mike deploy -u dev
    - name: Deploy
      run: git push origin gh-pages:gh-pages
