name: Repo

on:
  push:
    branches: [ release ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge release -> develop
      uses: everlytic/branch-merge
      with:
        target_branch: develop
